### ISSUE TITLE
关于模型训练，我们发现在第二轮训练时会出现模型不在cuda的问题

### ISSUE THREAD

**Issue by Zhou-wy** [hli1221/imagefusion-rfn-nest#9]
在train_fusionnet.py中第211-232行缩进是否有问题？
按照我的理解，如果按照公布的源码训练，在第一轮训练后模型移往CPU，在第二轮训练开始后，模型在CPU 上，无法训练。应该把rain_fusionnet.py中第211-232行往前缩进吗？

**Comment by hli1221** [comment]
谢谢你的反馈。
很抱歉，这确实是我的失误，最终保存模型的代码在整理程序时缩进太多。
我已经重新修改，并提交了。
